### ISSUE TITLE
[CLASS][ARCHETYPE] "Profane Commandment" from Dread knight Conqueror Archetype is not scaling with levels nor charisma modifier

### ISSUE THREAD

**Issue by Random-QA-Analyst** [ka-dyn/ExpandedContent#55] opened 2022-10-02 10:09 UTC
Hello, 
I have found a class-breaking issue regarding the Conqueror dread knigh archetype
It seems the "Profane Commandment" class feature from Dread knight Conqueror Archetype is not scaling with levels nor charisma modifier.

**Step to repro :**
1) Create a Dreadkight - Conqueror character with more than 14 Charisma (MC / Mercenary / Companion respec from scratch it doesn't matter)
1.1) Note the "Inspired Rage" feature is locked on 4 charges instead of (3+Cha.modif)
2) Level up the character
3) Note the "Inspired Rage" feature is locked on 4 charges instead of (3+2/level+Cha.modif)

**Result**
it seems the charges of Inspired Rage are not scaling accordingly with the class tooltip (that should duplicate the Skald scaling as 3+2/level+Cha.modif).

**Observations :** 
Note this bug apply for all Conqueror's raging song like Dirge of Doom and so on. Not only the Inspire Rage one.

**Additional infos**
You will find some screenshot for my game to witness the actual issue (with green-scared higlighted infos).
On my personal run, the issue is occuring on a full respec. Regill .

Best regards and thx you for this wonderful mod

![DK_Bug1 2](https://user-images.githubusercontent.com/114856142/193448866-b30879a9-2a83-4504-9b9f-301052257e4a.jpg)

A random QA Analyst
![DK_Bug1](https://user-images.githubusercontent.com/114856142/193448786-ecc35ad1-238c-4dc5-9fef-42f99c1b9468.jpg)

**Comment by bittercranberry** [comment] 2022-10-02 11:56
I'll see if I can get this sorted for the next update.
Thanks for the extremely clean bug report!

**Comment by bittercranberry** [comment] 2022-10-02 18:52
Will be fixed for a release later tonight.
Can't test properly due to my location so I'll leave the ticket open until you confirm it works as intended.

**Closed** 2022-10-04 15:36 UTC
Labels: bug
