### ISSUE TITLE
Philosophies can take Inquisitor levels but not cast spells?

### ISSUE THREAD

**Issue by Deiwos** [ka-dyn/ExpandedContent#114] opened 2023-08-15 12:27 UTC
**Describe the bug**
I multiclassed Inquisitor onto Camellia and her Inquisitor spells state they are disabled due to 'Wrong alignment' despite apparently having an alignment that's just fine for taking *levels* in Inquisitor. I tried respeccing with Hilor after the mod was installed and this still is the case. Shaman spells still work, and Bane Weapon and Inquisitor domain powers work fine. Oddly enough she has two different Green Faith icons in her Abilities list. I don't notice that with anyone else, including Ulbrig who is also Green Faith.

With a bit of testing I've found that you can't even select the Philosophies dropdown in the Deity Selection if you take Inquisitor at level 1, but nothing prevents taking levels after that unlike, say, Monk or Paladin.

**Expected behavior**
There should be no reason Inquisitor spells would be affected by alignment if the character has the right alignment to take levels in the class.

**Screenshots**
https://i.imgur.com/ioUCppA.jpg
https://i.imgur.com/TKwBTou.jpg

**Additional context**
Mod list:

```
- ToyBox
- Brawler Class
- DarkCodex
- Expanded Content
- Kineticist Elements Expanded
- Microscopic Content Expansion
- ModMenu
- More Relic Info
- Puzzle Skip
- Respec Mod
- Scaling Cantrips
- Tabletop Tweaks Base
- Tabletop Tweaks Core
- Tabletop Tweaks Rework
- Tome of the Firebird
- Weapon Focus Plus
```
(Note: Toybox's "Ignore alignment when choosing a class" setting is disabled.)

**Comment by bittercranberry** [comment] 2023-08-17 07:47
I'll have a look but the issue is most likely that expanded content hardlocks the companions deity options (to prevent larger bugs) and as you are forcing a new deity via respec mod they are conflicting.
I think I documented this on the nexusmods FAQ so can you check if that seems to be whaf is happening?  If you look in Cams feature list she should still have the green faith.

**Comment by Deiwos** [comment] 2023-08-17 12:32
Those screenshots were actually taken after doing a normal respec with Hilor, and I don't use the Respec Mod option 'Change Background/Deity' so I haven't forced anything. I did try turning that on and then _not_ selecting a deity during the respect process and that didn't fix it either. It seems she's permanently stuck with both the right and wrong Green Faith, heh.

**Comment by bittercranberry** [comment] 2023-08-17 12:59
Once a deity has been added normal respec will not remove it. If you what to fix casting you will need to remove one of them using Toybox.
The issue is most likely a Cam thing as she is a bit of a mess due to having a faith that stops divine casting on her alignment.
I'll have a look on the weekend to try to replicate the bug.

**Comment by Deiwos** [comment] 2023-08-17 13:01
I'm currently playing around with Toybox trying to figure out how to remove it actually, heh. It doesn't seem to be a normal property that is exposed.

**Comment by Deiwos** [comment] 2023-08-17 14:20
So if I remove what I assume is this mod's version of Green Faith she gets her spells back. If I remove what I assume is the base one, she lacks the ability to cast them, and then she gets it back after reloading the game.
Another thing to note is that the specific thing it's called according to ToyBox is GreenFaithCamelliaFeature vs this mod's GreenFaithFeature which is possibly why it doubled up rather than overwriting. Other companions don't seem to refer to it in that manner.

**Comment by bittercranberry** [comment] 2023-08-17 14:45
This mod does not add green faith it just let you pick it before Owlcat let you in a past update.
The Camellia one is most likely the fix for normal green faith not working so keep that.

**Comment by bittercranberry** [comment] 2023-09-15 12:38
The issue with Cam will be resolved in the next update.

**Closed** 2023-09-16 22:22 UTC
Labels: bug
