### ISSUE TITLE
Shaman - Heavens Spirit - Guiding Star Hex

### ISSUE THREAD

**Issue by Kshumishyn** [ka-dyn/ExpandedContent#136] opened 2024-01-09 01:19 UTC
**Describe the bug**
I tried the Heavens Spirit for the first time upon discovering (in-game) that it has a really awesome Hex called Guiding Star. As attached in the first picture, it claims to add my Charisma Mod to all Wisdom-based checks. To my dismay it in-fact does not.

Not only this, but upon noticing this, I went to check the PFSRD for the Spirit to see if I am misunderstanding how it works, and the phrasing of the description is incorrectly translated into this mod. I linked the PFSRD Page below, But to quote it here:
_"can add her Wisdom modifier to her Charisma modifier on all Charisma-based skill checks"_

So, it's not supposed to be for all checks, just skill checks, and it's the other direction, WIS to CHA checks, not CHA to WIS checks. I'm not sure what the expected behavior is, but it currently doesn't do what it says, ~and I can't see it doing what it's supposed to be doing according to the PFSRD~. I can see now that it is in-fact adding my Charisma Mod to my Wisdom Skills as an "Other" entry.

**Screenshots**
![image](https://github.com/ka-dyn/ExpandedContent/assets/28957257/7149b1a9-fbb3-4975-ba35-a25442e7dbec)

**Additional context**
[PFSRD Entry for Heavens Spirit](https://www.d20pfsrd.com/classes/hybrid-classes/shaman/spirits/heavens/)

**Comment by bittercranberry** [comment] 2024-01-09 11:33
I will fix the text in the next update.
I may be misunderstanding, are you saying it works as intended?

**Comment by Kshumishyn** [comment] 2024-01-09 20:16
> I will fix the text in the next update. I may be misunderstanding, are you saying it works as intended?

Sorry I was still experimenting a bit so the live updates got a bit messy. It's close to intended behavior but it misses the mark.

The mod is not consistent with Tabletop PFSRD in the following ways:
- Cosmetically, the description does not match and is between very misleading and wrong.
- Functionally, it's adding the wrong stat. It's supposed to be adding Wisdom Mod to Charisma skills. Currently the mod is adding Charisma Mod to Wisdom Skills.

I don't know if there are any other issues. Does that help clarify?

**Comment by bittercranberry** [comment] 2024-01-10 21:29
Fixed in the next update.

**Comment by bittercranberry** [comment] 2024-01-29 20:11
Updates out, thanks for the help!

**Closed by bittercranberry** 2024-01-29 20:11 UTC
Labels: bug
